### PR TITLE
Make 'Split page' support posters

### PR DESCRIPTION
**Pull request by ole-tange**
Closes: https://github.com/pdfarranger/pdfarranger/issues/327

### CODE REVIEW

**Review by angsch — COMMENTED** [review]
On testing, I found a few problematic cases.

### Zero-dimensional pages

Pages where either the column width or the row height is zero will create a thumbnail that can be exported and yields an illegally sized page.

Reproduce
- Split a page
- Untick equal column width
- Increment vertical splits

Please add a check so that we do not get empty pages.

### Uneven splits

If you set the sizes manually, the splits are evenly sized, regardless of whether or not the checkbox equal column width/row height is ticked.

Uneven splits, say 33% + 67%, are still supported, but it is more difficult. The following works:
- Untick equal column width
- Increment vertical splits
- Tick equal column width
- Untick equal column width
- Decrement vertical splits

I am ok with not supporting uneven splits, but then I suggest to remove the checkbox equal column width/row height and keep equal sizes all the time.

### Content loss possible

The targeted content overlap implicitly assumes that the sizes add up to at least 100 %. If this is not the case, the center parts of the page are lost.

Reproduce
- Split a page
- Overwrite col 1 width with 30%. This will automatically adjust the width of the second column to 30%.

The result is two pages showing the leftmost 30% and the rightmost 30%. The center part is lost. I suggest to add a check that `crop_sum` is at least 100.

### Other comments
Did you possibly forget to adjust the comment in line 144? The calculation for the size of the i-th slice is `crops[2*i+1] - crops[2*i]`.

**Comment by dreua** [comment]
I just realized that "dreua added this to the 1.8.0 milestone" could be misunderstood: All I actually wanted to say is, that this should not go into 1.7.x, but that's quite obvious. It's a nice to have feature but not a must have for 1.8 therefore I'll remove the milestone again.

**Comment by angsch** [comment]
That conflict is ... unexpected. Does someone know how to exclude that file from the PR so that we do not get a merge commit?

**Comment by jeromerobert** [comment]
@angsch `git rebase -i`, edit the culprit commit, unstage the `.pot` file, `push -f` the branch again.

**Comment by jeromerobert** [comment]
@angsch I did it and pushed https://github.com/pdfarranger/pdfarranger/tree/poster

**Comment by angsch** [comment]
@jeromerobert  Thank you!

The changes adjust ole-tange's version such that overlap is only possible if the splits have equal size. The overlap is then evenly distributed. I do not see a way to generalise overlap to uneven splits.

It was quite a bit of rewrite and if any of you have time to test, that would be great.

**Pull request closed without merging**
