### PR TITLE
Scroll the view with up/down & page up/down keys

### PR DESCRIPTION
**Pull request by kbengs**
* Scroll a small step up or down with arrow keys. 
* Scroll to previous/next page row with page up/down keys
* Disable the iconview built in "move cursor" function

I wasn't sure if it should scroll just a bit or a whole page on keyboard arrows. What do you others think about this?

### CODE REVIEW

**Comment by dreua** [comment]
I personally would like to keep the possibility to move the cursor by keyboard, it works well if you just want to select a single page. I'm quite sure I used it a few times on the laptop because I don't like touch pads. I'm open for discussion though, maybe I'm missing a point? Maybe Shift+Arrows could be used for scrolling as an alternative.


(OT: If we hadn't bound page rotation to Ctrl+Left/Right one could even select multiple pages by Ctrl+Arrows+Space. (You can try this now, but only with Up/Down, so only in one column which is not really useful. Should we switch to Alt+Left/Right for rotation to fix this?)

**Comment by kbengs** [comment]
My (maybe not so good) arguments for removing it was that it isn't working perfectly now. (because it doesn't scroll if cursor goes of screen) And therefore I guess that not many use the feature. This commit would give a possibility to scroll with keyboard. 

Stepping one page at a time up/down would make it work better as a pdf viewer. (as next step I was planning to try to find a way to do #51)

Would it be best if:
* The built in move cursor is not removed. Instead it would start to scroll when cursor otherwise would go of screen? (as for example nautilus works)
* Page up/down would step one page row at a time, as it already does in this commit?

Shift + arrows already works for selecting multiple pages.

**Comment by dreua** [comment]
Yes, that would be ideal imo. I usually have small PDFs which fit in one screen, therefore I wasn't aware of this problem.

> Shift + arrows already works for selecting multiple pages.

You're right, my bad.

**Comment by kbengs** [comment]
OK, a new try.

**Review by jeromerobert — APPROVED** [review]
Approving.

**Pull request merged**
