### PR TITLE
Add more languages

### PR DESCRIPTION
**Pull request by mapi68**

### CODE REVIEW

**Comment by dreua** [comment]
I think there is something wrong with this PR

**Comment by jeromerobert** [comment]
@mapi68 I guess that's this is automated translation. Which tool did you use ?

**Comment by mapi68** [comment]
ChatGPT

**Comment by jeromerobert** [comment]
I'm sorry but there are by far too many mistakes in this PR. You removed Name and change Comment (so all translations are wrong) in the .desktop for example.  Also please don't bump the version.

**Comment by mapi68** [comment]
But now .desktop file is complete

Screenshot_20240224_184648

**Comment by dreua** [comment]
I'm against using AI generated translations, I don't trust those systems and there is no way I could verify them and I don't think you could or have verified them either. Thanks for the initiative but I'm against merging this.

**Pull request closed without merging**
