### PR TITLE
Add range selection for pages

### PR DESCRIPTION
**Pull request by bilgetutak**
As discussed in #861 
 Added RangeSelectDialog class to handle the range selection.
- Added menu item to select menu and select context menus.
- Added range_select_dialog method to pdfarranger.py for completing the range selection.

### CODE REVIEW

**Review by kbengs — COMMENTED** [review]
There are exceptions if you write a page number that does not exist. Also if you write a character.

But other than that it appears to work well. I suggest you wait for comments from other reviewers before doing changes.

**Comment by kbengs** [comment]
Can you fix what was commented here? Also good if you can rebase/squash/fixup so all is in one commit.

**Comment by dreua** [comment]
@bilgetutak are you interested in following up here? Is anyone else? Otherwise I propose to copy this branch to our repo for further reference and close this stale pr.

**Comment by bilgetutak** [comment]
I am sorry @dreua. I was in a long project commitment, just delivered. I will work on it this week, if not I will close. Thanks for reminding.

**Comment by bilgetutak** [comment]
I have reviewed the comments here, and I believe I fixed them all. All changes in one commit this time (reversed my original fork).

**Comment by kbengs** [comment]
Appears to work. A few comments on what I notice:
* You should use `self.range_entry_widget.set_activates_default(True)` Then `Enter` will close the dialog.
*  ,,,,,, and ---- causes issues
* Maybe change the label to:
  ```
          label=_(
                  'Use a comma to separate page numbers, '
                  'a dash to select a range of pages. \n'
                  'e.g. : "1,3,5-7,9"'
              )
  ```
(I added a missing space and remove 'Page range to select.') And place the label under the entry instead of above? (not sure)
* The `selection` variable is not used (I think it's fine that you unselect all before selecting the range)
* The variables `action, option, _unknown` are not used?

**Comment by bilgetutak** [comment]
> Appears to work. A few comments on what I notice:
> 
> * You should use `self.range_entry_widget.set_activates_default(True)` Then `Enter` will close the dialog.
> * ,,,,,, and ---- causes issues
> * Maybe change the label to:
>   ```
>           label=_(
>                   'Use a comma to separate page numbers, '
>                   'a dash to select a range of pages. \n'
>                   'e.g. : "1,3,5-7,9"'
>               )
>   ```
> 
> (I added a missing space and remove 'Page range to select.') And place the label under the entry instead of above? (not sure)
> 
> * The `selection` variable is not used (I think it's fine that you unselect all before selecting the range)
> * The variables `action, option, _unknown` are not used?

* I think most of them are fixed. Except user can enter really weird selection cases like `,-,` or `-,-` or `,    ,`. Most of these don't really do any selection, or select the entire model.
* I tried to prevent typing any of the special characters twice (probably possible through copy-paste though).
* I intended to implement an additive range selection (add on top of previous selection), but not sure if it is useful. I had the `selection` variable because of that. Currently removed it. In the future might be added. 
* Not sure about the `action, option, _unknown`, I kept them for compatibility with all the other functions. Not really used otherwise.

**Comment by kbengs** [comment]
> Not sure about the action, option, _unknown, I kept them for compatibility with all the other functions. Not really used otherwise. Maybe for tests, when implemented?

You should remove them here, as they are not used. They can be added later if needed. Can you also remove `# self.set_activates_default(True)` Then rebase and fixup all in one commit again. Then I think it's all good. :-)

**Comment by kbengs** [comment]
@bilgetutak it is currently in a state so that it can not be merged. The commits would need to be moved to top of the main branch. And ideally in one commit. If you do not want to/can't fix it I can do it.

**Comment by bilgetutak** [comment]
@kbengs I actually thought that I did reduce it in to one commit, but I didn't have experience with it before and I think I had trouble (gotta get better with git :)). If not much trouble, can you complete it. Much appreciated.

**Comment by luzpaz** [comment]
soft bump :smiling_face_with_tear:

**Comment by kbengs** [comment]
merged as dde8fa14c004a93626a89a42fc8de168981d5488

**Pull request closed without merging**
