### PR TITLE
Fix regression in #957

### PR DESCRIPTION
**Pull request by m-holger**
To reproduce:

- open tests/test.pdf
- Merge the two pages
- Export

The green rectangle is lost.

Reported by @kbengs in #961

### CODE REVIEW

**Comment by m-holger** [comment]
@kbengs

I believe that the PR fixes the issue, could you please verify.

Dogtest batch 2 fails with the fix. I think this is a problem with the test. When I go through the test sequence manually, with the fix the page 1 output matches the rendered image on screen as well as the output produced by the flatpack version of PDFArranger. Without the fix, page 1 output is different.

Is there an idiot's guide to running the dogtest suite locally somewhere?

**Comment by kbengs** [comment]
It appears to fix the problem!

If you want one more I have one: :-)
To reproduce:

* Open tests/test.pdf
* Rotate the green rectangle  to the left
* Merge the two pages 

The green rectangle does not look as it should in the iconview

I run the test with:
`rm ~/.config/pdfarranger/config.ini`
`python3 -X tracemalloc -u -m unittest -v -f tests.test`

For me it fails at test_03_booklet (tests.test.TestBatch5) But this might be some problem on my machine only...

**Comment by m-holger** [comment]
> I run the test with: ...

Thanks. That was easier than expected. From testing.md I was under the impression that it required to be run in a docker image.

> If you want one more I have one: :-)  ...

That seems to have been a local problem. It passed for me.

I slightly changed the file size for the output for batch2. I think the batch works correctly but someone needs to verify it.

**Comment by jeromerobert** [comment]
> Is there an idiot's guide to running the dogtail suite locally somewhere?

To run in docker/podman: https://github.com/pdfarranger/pdfarranger/blob/main/TESTING.md#dogtail. This is good to reproduce what happen in Github Action but you won't see the UI.

Some tips when running out of docker: https://github.com/pdfarranger/pdfarranger/blob/main/tests/test.py#L36-L40

> Dogtail batch 2 fails with the fix. I think this is a problem with the test. 

I check the size of the exported files to check it has the expected number of triangles, that is the "past as overlay" added a second triangle to the page. The tolerance may be too small but this may also be suspect.

**Comment by m-holger** [comment]
I fixed the line in PDFRenderer and added some code to explicitly check for the expected triangles

**Comment by m-holger** [comment]
@kbengs 

>    If you want one more I have one: :-) ...
> That seems to have been a local problem. It passed for me.

Sorry, that was meant as a response to 

> For me it fails at test_03_booklet (tests.test.TestBatch5)

**Pull request merged**
