### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by uwe-ss**
Minor fixes in de,po

### CODE REVIEW

**Review by dreua — CHANGES_REQUESTED** [review]
This is only changing typography: Can you explain why you changed this? We want to keep it as close as possible to other GNOME and Linux Software and I think this is not the style used by the majority, but I'd need to check to be sure as using English UIs despite my mother toungue.

**Comment by dreua** [comment]
@jeromerobert Thanks for the reminder I saw this PR but then forgot about it.

**Comment by uwe-ss** [comment]
> We want to keep it as close as possible to other GNOME … Software

Exactly that was my intend. Have a look at [https://wiki.gnome.org/de/UebersetzungsRichtlinien](url)

**Comment by dreua** [comment]
I stand corrected, thank you for improving the translation and the helpful link. I guess having german as my first language doesn't make me a good translator when I never use translated software :thinking:

**Pull request merged**
