### PR TITLE
Remove iconview viewport

### PR DESCRIPTION
**Pull request by kbengs**

### CODE REVIEW

**Comment by jeromerobert** [comment]
Awesome. I'll fix the dogtail tests before merging.

**Comment by dreua** [comment]
> Close pdfarranger#505, Close pdfarranger#506

Awesome, thank you!

**Comment by kbengs** [comment]
I changed a variable name and added two more commits.

**Comment by dreua** [comment]
Does this also fix #501 ?

**Comment by kbengs** [comment]
> Does this also fix #501 ?

No I left that one for you. ;-)

**Comment by jeromerobert** [comment]
Merge as 39e13cb408ae31255ffbb99e61cc2d6af252ab1b to 5000778089d5a85e44a6255304ed343f28681697. Added 7b04803a6d1b5078420422a7af047d3d2648f323.

**Pull request closed without merging**
