### PR TITLE
Change behavior when navigating with keyboard keys

### PR DESCRIPTION
**Pull request by kbengs**
Draft for #296
* When navigating in iconview with left/right arrow, continue on
  previous/next line when end of a line is reached
* When selecting with keyboard navigation keys, select all pages
  between cursor and page where cursor was when shift was pressed

The reason for the complicated unselect approach is that plain unselect_all() is too slow for example when shift + down arrow is pressed and the key is auto repeated.

There is a unsolved issue here: if a page is selected with mouse click and you try to continue to move cursor with arrow keys, the cursor will be invisible (the dashed rectangle is not visible).
Any ideas or comments so far?

### CODE REVIEW

**Comment by jeromerobert** [comment]
I think it's good to be merged.

This is nothing new with this pull request, but we are triggering too many `selection_changed` events (`iv_selection_changed_event`). `Ctrl+A` trigger few events, but selecting the first page then doing `shift+end` trigger at least one event by page. The reason for this is that `Gtk.IconView` only allow programmatic selection of one page at a time (`select_path`). Each `select_path`do a lot of things (https://github.com/GNOME/gtk/blob/3.24.23/gtk/gtkiconview.c#L3365). We should disable our `selection_changed` while doing large selection changes. This could look like this:

```python
with iconview.edit_selection(): #__enter__ disable event handler
    # do all selection changes
    iconview.unselect_all()
    for x in foobar:
        iconview.select_path(x)
    #__exit__ restore the event handler
```     
Unfortunnatly there is nothing we can do about `gtk_icon_view_item_selected_changed` and `gtk_icon_view_queue_draw_item` calls, they cannot be disabled.

Anyway this problem is not perceptible and so by far not critical.

**Comment by kbengs** [comment]
> but we are triggering too many selection_changed events 

Yes I noticed that a auto-repeated shift + down arrow will cause my older laptop to lag. If I block selection_changed event it works fine. So I think we have to block it as long as shift is pressed and unblock when key is released. I will try to make a fix for that and also I would like to find a solution for the invisible cursor.

**Comment by kbengs** [comment]
It should be okay now.

**Comment by jeromerobert** [comment]
You're a GTK guru :-)

**Pull request merged**
