### PR TITLE
Fix iconview in right-to-left locale

### PR DESCRIPTION
**Pull request by kbengs**
This fixes:
* Drag and drop of pages
* Dragging in a file
* Selecting pages by clicking and dragging mouse
* Navigating and selecting with keyboard arrows

### CODE REVIEW

**Comment by kbengs** [comment]
Looks like `./setup.py build` does not create `build/mo` since 3477ee615d089483d36337a9c1adeda4d97b3df3

Tried to "fix" it with 307958c2dc0c29779b1f3f4e160bb9a325c978f0 but I guess os.name does not return 'nt" here

Any ideas how to fix it properly?

**Comment by jeromerobert** [comment]
> Looks like `./setup.py build` does not create `build/mo` since [3477ee6](https://github.com/pdfarranger/pdfarranger/commit/3477ee615d089483d36337a9c1adeda4d97b3df3)

I'm on it.

**Comment by jeromerobert** [comment]
This is very odd:
- https://github.com/pdfarranger/pdfarranger/commit/3477ee615d089483d36337a9c1adeda4d97b3df3 built one time properly: https://github.com/pdfarranger/pdfarranger/actions/runs/6208430514/job/16936487582
- I cannot reproduce the issue when running in Docker locally with the very same Docker image
- In Github Action https://github.com/pdfarranger/pdfarranger/blob/3477ee615d089483d36337a9c1adeda4d97b3df3/setup.py#L103 seems to have no effect
- It remind me https://github.com/pdfarranger/pdfarranger/issues/972 but I tried to upgrade setuptools and python with no luck
- A workaround is to explicitly invoke `./setup.py build_i18n`. I'll push that if I cannot quickly find good fix.

**Comment by jeromerobert** [comment]
This is the same bug as https://github.com/pypa/setuptools/issues/4040. Any package can override the distutils or setuptools build command. In our case the culprit is also distutils-extra because it's still in the build Docker image even if we no longer use it. In general we cannot assume that `./setup.py build` will be either `setuptools.command.build` or `distutils.command.build`. It can be anything. I'm looking for a clean solution.

**Comment by jeromerobert** [comment]
https://github.com/pdfarranger/pdfarranger/pull/986

**Comment by kbengs** [comment]
Tested in Ubuntu 23.04 with language set to Hebrew. As far as I can see it works.

**Pull request merged**
