### PR TITLE
Resolves #240

### LINKED ISSUE #240: Add "Export selection to individual files"
Hi. Currently the "Export selection" option working to export all selected page into single output PDF.

Can you, kindly, added option to "Export selection" into individual PDF files (each selected page should exported into independent PDF file) ?

### PR DESCRIPTION
**Pull request by angsch**
Add two more export options, 'export selection to individual files' requested in #240 and 'export all pages to individual files'.

### CODE REVIEW

**Comment by Nokia808** [comment]
@angsch 
Thank you for this PR !
Only one note: with "export to individual files" options, the output files should be without the outlines (TOC) that may some time already existing in original (input) PDF. For example, if I have a PDF has outlines (TOC) for it's 17 chapters & their sub-chapters, it will be meaningless if each of extracted individual files (that each of them represent a single page of original PDF) has TOC of original file.

I'm nearly sure you are already addressed this, but since I'm not programmer I give this note to avoid post implementation fix ....

Best regards.

**Comment by kbengs** [comment]
Some observations when I tested it:
* When starting this is printed to terminal: "SyntaxWarning: "is" with a literal. Did you mean "=="? if exportmode is 'ALL_TO_SINGLE':"
* Mnemonics accelerators are missing in menu.ui (Keyboard shortcuts, Alt + X) Could be for example "Export Specia_l…"
* "export selection" and "save as" are always greyed-out in hamburger menu (or am I missing something?)
* Export options are only available in right-click menu, shouldn't they be in hamburger menu also?

But overall I think it looks good.

**Comment by angsch** [comment]
@kbengs 
Thanks for testing. It is really good that you point of the thing with the hamburger menu. I am gonna fix your points. Thanks, again.

**Comment by jeromerobert** [comment]
Thank you @angsch. You PR looks good. Here is what I would add to kbengs comments:
* I think "Export selection" is already something "special". So I would prefer that you rename "Export Special..." to "Export..." and move "Export Selection" to it.
* I also think that the new export submenu should be in the hamburger menu.
* Could you also rebase your branch to master and remove the merge commit ?

**Comment by angsch** [comment]
The code has been revised according to your comments. I think it is ready for being merged.

**Comment by kbengs** [comment]
Two small things I still notice:
* You probably forgot to remove the line: "attribute name="target" type="i">0</attribute" from the "save as" section in menu.ui
because save as in hamburger menu is still always greyed-out
* Empty line in menu.ui line 320

**Comment by kbengs** [comment]
CTRL+F is usually shortcut for find, maybe something else should be used here?

**Comment by jeromerobert** [comment]
I merge it, we'll fix that kind of details.

**Comment by jeromerobert** [comment]
56b3150

**Pull request merged**
