### PR TITLE
Fix unit/scaling issue when printing on Windows

### LINKED ISSUE #806: Printing doesn't work right - printed document is too small, doesn't fill whole page
Describe the bug
----------------

No matter what I try to print, it prints like this: 

image
(picture cropped because of space)

It's like this even when printing through _Microsoft Print to PDF_ service.
If I check "show print preview" in the printer settings*, it looks the same there as well; I don't even need to print it physically. (but it will look the same when I do)

'* my printer is a Kyocera M3540idn

To Reproduce
------------

Try to print anything... 
It will put out something like the picture above, or the attached bad printing.pdf file. (that file I printed using the Microsoft Print to PDF service, but physically printing it resulted in a same look.)
See [bad printing.pdf](https://github.com/pdfarranger/pdfarranger/files/10345965/bad.printing.pdf)

Expected behavior
-----------------

Well, I was expecting it to print to the full page. In Acrobat it printed without problem.

Input files
-----------

Result: [bad printing.pdf](https://github.com/pdfarranger/pdfarranger/files/10345965/bad.printing.pdf)
Original file: [U4684 ...1594 Iveco Daily plató + ponyva megrendelő Bene.pdf](https://github.com/pdfarranger/pdfarranger/files/10345966/U4684.1594.Iveco.Daily.plato.%2B.ponyva.megrendelo.Bene.pdf)

The issue is not unique to these files, I tried to print a bunch of others with the same results; I attached these for reference only.

System and Versions
-------------------

-   PDF Arranger version: 1.9.2, downloaded from GitHub, portable version.
-   pikepdf version and where you get it:
    From the _About_ menu:  libqpdf 10.4.0, pikepdf 4.3.1, GTK 3.24.31 and Python 3.9.7 (downloaded the portable version, with these included)
-   OS name and version:
**Edition**: Windows 10 Pro
**Version**: 22H2
**Install date**: ‎2021. ‎05. ‎21.
**build nr.**	19045.2364; Windows Feature Experience Pack 120.2212.4190.0

### PR DESCRIPTION
**Pull request by jeromerobert**
Fix #806

### CODE REVIEW

**Comment by galgogergo** [comment]
Hi! As I'm new to GitHub, I'd be grateful is you told me what Pull Requests are! (I was the one who opened bug report #806 ) Does opening this "pull request" mean that the problem is now solved? Should I download the latest version? But it says 1.9.2, the same which I have, and is buggy. 
Or may I download the files above, and paste them into the program folder?

**Comment by kbengs** [comment]
A PR is a proposed change. This is still in "draft" meaning it is still a work in progress.

You can find a zip/msi with this PR included on the actions page:
https://github.com/pdfarranger/pdfarranger/actions/runs/3932931921

But it does not yet work. I have tested. :-)

**Comment by jeromerobert** [comment]
Indeed it does not work, a I currently have no other idea :-(.

**Comment by jeromerobert** [comment]
Tested on Windows 10 and Debian testing/12 on few documents.

**Pull request merged**
