### PR TITLE
Set minimum pikepdf version to 1.17.0

### LINKED ISSUE #460: About bumping pikepdf version requirement
> We may want to consider updating the dependency on the pikepdf version.

> I think requiring pikepdf >- 2.8.0 might be a good idea

Unfortunately, when packaged for Linux distros, requiring something which is too new is a problem because the pikepdf package may not be available in a sufficient version.

Repology seems to be a good source for more information on packaged versions: https://repology.org/project/python:pikepdf/versions

I once created this version Matrix with repology, maybe it can help with the decision-making - editing the URL should be quite self-explanatory:

https://repology.org/badge/versions-matrix.svg?projects=pdfarranger,python:pikepdf%3E=1.7,pdfshuffler&header=pdfarranger%20packaging%20status

I know that the pikepdf-Fedora-package-maintainers won't update to 2.x during a release because they consider this a major release (It is according to [Semantic Versioning](https://semver.org/lang/de/) because it goes from 1.x to 2.x, not sure if that is actually a breaking change in pikepdf that would prevent upgrading.) At any rate, the fallout should be carefully considered before raising the required versions. Probably in its own issue for better clarity and structure.

Edit: I could try discussing and fixing this for Fedora with the pikepdf maintainers. However, there are many distributions and I expect them to have very similar rules and problems.

_Originally posted by @dreua in https://github.com/pdfarranger/pdfarranger/pull/459#issuecomment-815672525_

### PR DESCRIPTION
**Pull request by jeromerobert**
* All major distro now have it
* Drop a workaround for https://github.com/pdfarranger/pdfarranger/issues/141 /
  https://github.com/pikepdf/pikepdf/issues/80
* Close #460

### CODE REVIEW

**Comment by dreua** [comment]
I think your part of the CI is failing, no idea why: `/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cmd_class'`

**Review by dreua — APPROVED** [review]
Changes look good to me. Feel free to merge, but we might have a closer look at the failing CI first.

**Comment by dreua** [comment]
Found the reason for our CI-fail: https://github.com/pikepdf/pikepdf/commit/19b9b0391e8abc00905cea2df4ce0f1c6c0bb9c2#

**Comment by jeromerobert** [comment]
Changing to draft, until I fix `pip install pikepdf`.

**Comment by jeromerobert** [comment]
I think I'm just going to upgrade the CI docker image to Alpine 3.13.5

**Comment by dreua** [comment]
btw: there is a "Rerun Jobs" button at the top right of [the action pages](https://github.com/pdfarranger/pdfarranger/actions/runs/783552216). Looks like you were not aware of that.

**Pull request merged**
