### PR TITLE
Add Italian translation

### PR DESCRIPTION
**Pull request by mapi68**
Added Italian translation, fix language order and xml formatting.

### CODE REVIEW

**Comment by dreua** [comment]
For proper review those need to be split up in 3 commits. Furthermore I'm not sure we want to change the formatting, are there good reasons to do that?

**Comment by dreua** [comment]
Nitpick: Commit comments should be in present tense, I.e. Add instead of Added.

**Comment by mapi68** [comment]
> For proper review those need to be split up in 3 commits. Furthermore I'm not sure we want to change the formatting, are there good reasons to do that?

Only cosmetic changes......

**Comment by mapi68** [comment]
> Nitpick: Commit comments should be in present tense, I.e. Add instead of Added.

You're right.

**Comment by dreua** [comment]
The [Freedesktop example](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) as well as [Nautilus](https://github.com/GNOME/nautilus/blob/master/data/org.gnome.Nautilus.appdata.xml.in.in) use two spaces indentation, therefore I won't merge a commit changing that to tabs without giving a very good reason.

I'd still like to add your translations, would you submit them without any other changes? (If you want to reorder, do that in a separate commit, please.) You may use `--force-with-lease`  to update this branch / PR.

**Comment by jeromerobert** [comment]
Superseded by #734

**Pull request closed without merging**
