### PR TITLE
Use normal clipboard in Linux

### PR DESCRIPTION
**Pull request by kbengs**
Could a wayland user test if this make copy-pasting work? (it does work in a virtual machine..)

### CODE REVIEW

**Comment by kbengs** [comment]
Tested in Gnome and KDE with wayland

**Comment by mara004** [comment]
Looks good, I'll check this out and test it soon.

**Comment by mara004** [comment]
Yep, I can confirm it works. Great.

**Comment by jeromerobert** [comment]
Great, it also simplifies the code

**Pull request merged**
