### PR TITLE
Improve menu

### PR DESCRIPTION
**Pull request by kbengs**
The wiki has a section about ellipsis in "computer systems":
https://en.wikipedia.org/wiki/Ellipsis

https://stackoverflow.com/questions/278655/when-should-i-use-a-ellipsis-in-a-menu-item

### CODE REVIEW

**Comment by kbengs** [comment]
I can add ellipsis to all languages before merging this

**Comment by jeromerobert** [comment]
> I can add ellipsis to all languages before merging this

Thank you. I think it has to be done. I can also do it. This is as you wish.

**Comment by kbengs** [comment]
I think I got all. I noticed that `./setup.py build` creates a .pot that is not sorted.

**Comment by jeromerobert** [comment]
> I noticed that ./setup.py build creates a .pot that is not sorted

Yes.  Not only this make the working directory "git dirty" but it also uses `intltool` which we would like to get rid of. I wonder if we should get rid of python-distutils-extra and handle the calls to `msgfmt`, the installation of `.mo` files and the installation of icons ourselves.

**Pull request merged**
