### PR TITLE
Fixes #449

### LINKED ISSUE #449: Page crop can exceed 100%
The check that crops of opposite sides sum to at most 99% can be bypassed. The export yields an unexpected PDF.

1. Open page format dialog, set left crop to 80, press OK.
2. Open page format dialog again, _type_ 80 into the right crop field, press OK.

The crop is accepted:
image

The exported PDF looks:
image

### PR DESCRIPTION
**Pull request by angsch**

### CODE REVIEW

**Comment by kbengs** [comment]
Should it limit the value that you currently try to set too high instead? Now it will trim down the left value if you set the right value too high.

**Comment by angsch** [comment]
> Should it limit the value that you currently try to set too high instead? Now it will trim down the left value if you set the right value too high.

When a user types in a value, I assume that this is really the value the user wants there.

**Comment by kbengs** [comment]
Yeah it can be seen that way too. Can be merged imo.

**Comment by jeromerobert** [comment]
Merged as 9f4fca0047a182fc0f35ed6f82bf25938fd90ccd (just added a commit title)

**Pull request closed without merging**
