### PR TITLE
Add libqpdf and pikepdf version numbers to About dialog

### PR DESCRIPTION
**Pull request by m-holger**
Minimal implementation of #439 

Adds the line 
```
(PDF Arranger uses libqpdf x.x.x and pikepdf x.x.x)
```
to the About Dialog . Also changes PDF Arranger website to a link.

### CODE REVIEW

**Comment by dreua** [comment]
Thanks for the PR!

Please link to the corresponding GH issue so everyone involved can easily navigate between the two. (Ideally add the full link to the commit message for future reference. Use Closes: <link> to automatically close the issue once the commit is merged.)

Two minor nitpicks: The two commits should be squashed into one. You may use the force (push -f) on your feature branch, it should automatically update this PR. And commit messages should be present tense (Add instead of Added).

**Comment by dreua** [comment]
You can fix those nitpicks as a git exercise or we can squash those before merging and leave the tense as it is, not that important imo. Your choice.

**Comment by m-holger** [comment]
@dreua Sorry, I was trying to  make a push request to my own repository and therefore didn't provide a comment until after I realised that this was a "live" push request.

Will update as per your suggestions tomorrow.   

Reminder - needs checking that string change does not cause runtime errors on non-English versions

**Comment by kbengs** [comment]
The code looks good to me. The commit message break the guidelines a bit: Subject line should not end with a dot. There should be a empty line between subject and body.

**Comment by m-holger** [comment]
This modification unnecessarily breaks the translation of the existing AboutDialog message

**Comment by dreua** [comment]
@m-holger What is the plan here?

**Comment by m-holger** [comment]
@dreua I am testing a modified implementation that preserves existing translations and will issue a new PR when done.

**Pull request closed without merging**
