### PR TITLE
Add Catalan translation

### PR DESCRIPTION
**Pull request by juxuanu**

### CODE REVIEW

**Comment by dreua** [comment]
Testing with `LANG=ca_ES pdfarranger` because only ca does not work (only the document title is translated in that case and a Warning gets printed). Looks good to me, can be merged once my previous question is addressed.

**Comment by juxuanu** [comment]
Hey! Catalan is the language, Valencian is a variation. The same way there are variations in Spanish for Mexico and Spain.

You can read more about it here: https://en.wikipedia.org/wiki/Valencian_language

**Comment by dreua** [comment]
Thanks for the quick reply! The Valencian variation seems to be pretty outdated (lots of untranslated strings): Any recommendation how to deal with it? Should we remove it in favor of your translation, i.e. can it be expected that people speaking "ca@valencia" are better served with your "ca" translation that with their current incomplete one?

**Comment by juxuanu** [comment]
They would understand it, yes, although the differences in some forms are very different. I'd guess there is nothing in my translation that any Valencian speaker would not understand.

**Comment by dreua** [comment]
Alright, I'll leave this for now, ideally the valencian translation would be updated, maybe we can find someone to do that.

@jeromerobert  do you have a list of translators per language somehwere? You should add @juxuanu and maybe ping someone for ca@valencia.

Thanks again for the translation and the PR :+1:

**Pull request merged**
