### PR TITLE
added snap manifest

### PR DESCRIPTION
**Pull request by soumyaDghosh**
I'll still my snap repo, so, that any changes needed can be done asap, and will push those changes here also. The snap will be built in the store from my repo. Like here I do.

https://github.com/NickvisionApps/Parabolic-snap

### CODE REVIEW

**Comment by soumyaDghosh** [comment]
Would you like to have a workflow?

**Comment by jeromerobert** [comment]
> Would you like to have a workflow?

Like a workflow which would automatically publish the snap ? How will it get your credentials ?

**Comment by soumyaDghosh** [comment]
Nah, that's done directly connecting my github repo in the store. A workflow to check if the snap is building, this will help you while implementing new features.
Also, kindly give me your mail, so that I can add you as a collaborator

**Comment by jeromerobert** [comment]
Ok, yes a checking if the snap is building would be nice, so we call you for help when it doesn't build any more.

jeromerobert@gmx.com

**Comment by soumyaDghosh** [comment]
Hi, I have done it. Added the workflow. Kindly test it if you want.

**Comment by soumyaDghosh** [comment]
Also I have sent you a collaboration request in the snap store

**Comment by soumyaDghosh** [comment]
Hii, I am keeping my repo, as it'll be served in the store. This manifest here is to test the snap with every single changes. I am trying to transfer that repo under this organisation. That will help me/us to serve the snap fast to the store. Just change the `source-tag` for `pdfarranger` part in that manifest file.

**Comment by soumyaDghosh** [comment]
kindly allow me to create public repositories under pdfarranger organisation and branches in this repo.

**Comment by jeromerobert** [comment]
I think I cannot give you rights to create a repository under pdfarranger without giving you full access to everything. I'll create the repo for you. `pdfarranger-snap` ?

You now have push access to pdfarranger/pdfarranger.

**Comment by soumyaDghosh** [comment]
I guess if I am a member your org then I can. I use the same model here also.

https://github.com/NickvisionApps

**Pull request merged**
